# -*- mode: ruby -*-
# vi: set ft=ruby :
# by Ramon

Vagrant.configure("2") do |config|

   config.vm.provision :shell, path: "bootstrap.sh"
   config.vm.synced_folder ".", "/vagrant"

  config.vm.define :puppet do |puppet|
        puppet.vm.box = "bento/centos-7.2"
        puppet.vm.hostname = "puppet.box"
 	puppet.vm.network :private_network, ip: "1.1.1.111"
        puppet.vm.provision :shell, path: "server_bootstrap.sh"
    	puppet.vm.provider :virtualbox do |vb|
               vb.memory = 3072
               vb.cpus = 2
    	end
  end

  config.vm.define :client do |client|
        client.vm.box = "bento/centos-7.2"
        client.vm.hostname = "client.box"
 	client.vm.network :private_network, ip: "1.1.1.112"
        client.vm.provision :shell, path: "client_bootstrap.sh"
  end

  config.vm.define :web do |web|
        web.vm.box = "bento/centos-7.2"
        web.vm.hostname = "web.box"
	web.vm.network :private_network, ip: "1.1.1.113"
        web.vm.network :forwarded_port, guest: 80, host: 8080
        web.vm.provision :shell, path: "web_bootstrap.sh"
  end

end
