# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "nginx2"
    d.name = "nginx2"
    d.ports = ["80:80"]
  end

  config.vm.synced_folder ".", "/vagrant"

end
