Vagrant.configure(2) do |config|
  # Ubuntu 12.04
  # start gui with startx
  # login u:vagrant, p:vagrant

  config.vm.box = "hashicorp/precise64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "tectonic" do |tectonic|
    end

  config.vm.provision :shell, path: "bootstrap.sh"
end
