Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 4444, host: 4444

  config.vm.define "tectonic" do |tectonic|
    end
end

