Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 5050, host: 5050
  config.vm.hostname = "mesos"

  config.vm.define "mesos" do |mesos|
    end
end

