# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "nginx"
    d.name = "proxy"
    d.ports = ["80:80","443:443"]
    d.vagrant_machine = "macbook"
  end

# config.vm.synced_folder "/temp", "/host_temp"

end
