# -*- mode: ruby -*-
# vi: set ft=ruby :
# by Ramon

Vagrant.configure("2") do |config|

  config.vm.provision :shell, inline: "apt-get update -y"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.define :web1 do |web1|
	web1.vm.box = "hashicorp/precise64"
        web1.vm.hostname = "web1.ramon.com"
	web1.vm.network :private_network, ip: "1.1.1.111"
	web1.vm.provision :puppet do |puppet|
         	puppet.manifests_path = "puppet/manifests"
         	puppet.manifest_file  = "web1.pp"
         	puppet.module_path = "puppet/modules"
  	end
	web1.vm.network :forwarded_port, guest: 80, host: 8081
  end

  config.vm.define :app1 do |app1|
	app1.vm.box = "hashicorp/precise64"
        app1.vm.hostname = "app1.ramon.com"
	app1.vm.network :private_network, ip: "1.1.1.112"
	app1.vm.provision :puppet do |puppet|
         	puppet.manifests_path = "puppet/manifests"
         	puppet.manifest_file  = "app1.pp"
         	puppet.module_path = "puppet/modules"
  	end
	app1.vm.network :forwarded_port, guest: 80, host: 8082
  end

end
